version: '3'

services:
  nuster:
    restart: unless-stopped
    hostname: cache.${VIRTUAL_HOST}
    container_name: cache.${VIRTUAL_HOST}
    image: nuster/nuster
    dns:
      - "1.1.1.1"
      - "9.9.9.9"
    volumes: 
      - ./nuster.cfg:/nuster.template:ro
      - ./init-nuster.sh:/init-nuster.sh:ro
    command:
      - "/bin/bash"
      - "/init-nuster.sh"
     environment:
        CACHED_PATH: ${CACHED_PATH:-/}
        CACHED_HOST: ${CACHED_HOST:-ietf.org}
#    env_file:
#      - .env
    logging:
      driver: ${DOCKER_LOG_DRIVER:-json-file}
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-20m}
        max-file: ${DOCKER_LOG_MAX_FILE:-10}
    sysctls:
      net.core.somaxconn: 1024

   
  cache:
    restart: unless-stopped
    image: nginx:alpine
    container_name: ${VIRTUAL_HOST}
    hostname: ${VIRTUAL_HOST}
#  ports:
#    - "8888:80"
    command:
      - "/bin/ash"
      - "-c"
      - "apk add --no-cache bash &&  bash /init.sh ;sleep 1"

    env_file:
      - .env

    volumes:
      - ./init.sh:/init.sh:ro
      - ./logformats.conf:/logformats.conf:ro
#      - ./varnish.vcl:/etc/varnish/default.vcl
#    cap_add:
#      - NET_ADMIN
    logging:
      driver: ${DOCKER_LOG_DRIVER:-json-file}
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-20m}
        max-file: ${DOCKER_LOG_MAX_FILE:-10}
    sysctls:
      net.core.somaxconn: 1024


networks:
  default:
    external:
      name: ${NGINX_NETWORK:-nginx-proxy}
